/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar/AppBar.vue')['default']
    Graph: typeof import('./components/Graph/Graph.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Metric: typeof import('./components/MetricBox/Metric.vue')['default']
    MetricBox: typeof import('./components/MetricBox/MetricBox.vue')['default']
    MetricsHeader: typeof import('./components/MetricsHeader/MetricsHeader.vue')['default']
    NavDrawer: typeof import('./components/NavDrawer/NavDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
